// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbOPAcIf8wDNELsZlruZPEklz66yHi1KY',
    appId: '1:711981599980:web:ffaa60f1b1d2f993f5a9c9',
    messagingSenderId: '711981599980',
    projectId: 'cocomart-a2e3c',
    authDomain: 'cocomart-a2e3c.firebaseapp.com',
    storageBucket: 'cocomart-a2e3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBqJpNxoDG1pVZGFEzJ0eDnK-OcYB3qMY',
    appId: '1:711981599980:android:2d56c2acdcaf563cf5a9c9',
    messagingSenderId: '711981599980',
    projectId: 'cocomart-a2e3c',
    storageBucket: 'cocomart-a2e3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDonsSRnvIzATP5rUzGOzRUmKAeUAW8_mg',
    appId: '1:711981599980:ios:da9026c9973b5029f5a9c9',
    messagingSenderId: '711981599980',
    projectId: 'cocomart-a2e3c',
    storageBucket: 'cocomart-a2e3c.firebasestorage.app',
    iosBundleId: 'com.example.cocomart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDonsSRnvIzATP5rUzGOzRUmKAeUAW8_mg',
    appId: '1:711981599980:ios:da9026c9973b5029f5a9c9',
    messagingSenderId: '711981599980',
    projectId: 'cocomart-a2e3c',
    storageBucket: 'cocomart-a2e3c.firebasestorage.app',
    iosBundleId: 'com.example.cocomart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbOPAcIf8wDNELsZlruZPEklz66yHi1KY',
    appId: '1:711981599980:web:82cc95abdb6932a7f5a9c9',
    messagingSenderId: '711981599980',
    projectId: 'cocomart-a2e3c',
    authDomain: 'cocomart-a2e3c.firebaseapp.com',
    storageBucket: 'cocomart-a2e3c.firebasestorage.app',
  );
}
